---
- include_vars: ../../vars/default.yml
- name: Install Mysql repo
#  - apt_repository: 
#    repo: 'ppa:mysql-5.7'
  get_url:  url=https://dev.mysql.com/get/mysql-apt-config_0.8.9-1_all.deb dest=/tmp/mysql-apt-config_0.8.9-1_all.deb mode=0644
#  state: present
#    apt: add-apt-repository -y ppa:ondrej/mysql-5.7 state=present 

- name: Install Mysql 5.7
  apt: pkg={{ item }}
  with_items:
   - mysql-server
   - mysql-client
   - python-mysqldb

- name: Start the Mysql service
  service: name=mysql state=started enabled=true


- name: Remove test database if exists
  mysql_db: name=test state=absent login_user={{ DB_USER }} login_password={{ Mysql_root_password }}

- name: Remove all anonymous user accounts
  mysql_user: name=""  state=absent login_user={{ DB_USER }} login_password={{ Mysql_root_password }}

- name: Change the root password
  mysql_user: name=root password= "{{ Mysql_root_password }}" login_user={{ DB_USER }} login_password={{ Mysql_root_password }}

- name: Create database for Artifactory
  mysql_db: name={{ Mysql_Database }} state=present encoding=utf8 login_user={{ DB_USER }} login_password={{ Mysql_root_password }}

- name: Create Artifactory user and Grant  Privileges
  mysql_user: name={{ Mysql_Username }} password={{ Mysql_Password }} priv={{ Mysql_Database }}.*:ALL state=present host={{ Mysql_Host }} login_user={{ DB_USER }} login_password={{ Mysql_root_password }}
